/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useState } from 'react';

const copy = {
  en: {
    navHome: 'Home', navAbout: 'About us', navProjects: 'Projects', navContact: 'Contact', quote: 'Request a quote',
    heroEyebrow: 'Built for Libya', heroTitleA: 'Groundwork for', heroTitleB: 'what comes next.', heroText: 'Earthworks, roads and heavy-equipment solutions delivered with the experience your project deserves.', startProject: 'Start a project', capabilities: 'Our capabilities', years: '30+ years of experience', operators: 'Skilled in-house operators', location: 'Benghazi, Libya',
    servicesEyebrow: 'What we do', servicesTitle: 'Practical expertise. Built to last.', servicesText: 'We bring people, planning and machinery together to make demanding sites move forward.', excavation: 'Excavation & earthworks', excavationText: 'Hard rock, soft rock, soil, pipelines and electrical trenches prepared with precision.', roads: 'Road construction', roadsText: 'Paved and unpaved roads built to approved regional specifications and project needs.', rental: 'Equipment rental', rentalText: 'Reliable heavy machinery backed by highly skilled, experienced operators.',
    footerText: 'Delivering complex infrastructure projects with practical management, honesty and integrity.', talk: 'Talk to our team', findUs: 'Find us', contact: 'Contact', address: 'Airport Road, in front of Al-Alban factory, Benghazi, Libya',
    aboutEyebrow: 'Our company', aboutTitle: 'Who we are', aboutText1: 'Ben Fadel General Construction Company is a leading earthworks and construction firm with over 30 years of experience delivering complex infrastructure projects across Libya.', aboutText2: 'Our proactive management style, honesty and integrity allow us to deliver lasting value for customers, suppliers and employees.', yearsExperience: 'Years experience', skilledOperators: 'Skilled operators', machines: 'Heavy machines', completed: 'Projects completed', team: 'Technical team', teamText: 'Supported by drivers, operators, mechanics and a specialist planning team, we bring precision to every project.', fleet: 'Machinery fleet', fleetText: 'Our fleet includes excavators, bulldozers, dump trucks, graders and specialist road-construction machinery.',
    contactEyebrow: 'Get in touch', contactTitle: 'Let’s build something lasting.', contactText: 'Tell us about your project and our team will get back to you promptly.', office: 'Office address', emailUs: 'Email us', callUs: 'Call us', formTitle: 'Request a quote', formText: 'Share a few details and we will prepare the right next step.', success: 'Thank you — your request has been sent. Our team will reply shortly.', name: 'Your name', email: 'Email address', phone: 'Phone number', projectType: 'Project type', projectLocation: 'Project location', startDate: 'Preferred start date', budget: 'Estimated budget', subject: 'Subject', message: 'Tell us about your project', choose: 'Choose one', excavationOption: 'Excavation & earthworks', roadOption: 'Road construction', rentalOption: 'Equipment rental', other: 'Other', budgetOption1: 'Under 50,000 LYD', budgetOption2: '50,000–150,000 LYD', budgetOption3: '150,000–500,000 LYD', budgetOption4: 'Over 500,000 LYD', send: 'Send quote request', privacy: 'By sending this form, you agree that we may use your details to respond to your enquiry.',
    whatsapp: 'Chat on WhatsApp', language: 'العربية', privacyLink: 'Read our privacy policy'
  },
  ar: {
    navHome: 'الرئيسية', navAbout: 'من نحن', navProjects: 'المشاريع', navContact: 'تواصل معنا', quote: 'اطلب عرض سعر',
    heroEyebrow: 'نبني ليبيا', heroTitleA: 'أساس متين', heroTitleB: 'لما هو قادم.', heroText: 'حلول لأعمال الحفر والطرق والمعدات الثقيلة، بخبرة يستحقها مشروعك.', startProject: 'ابدأ مشروعك', capabilities: 'قدراتنا', years: 'أكثر من 30 عاماً من الخبرة', operators: 'مشغلون مهرة ضمن فريقنا', location: 'بنغازي، ليبيا',
    servicesEyebrow: 'خدماتنا', servicesTitle: 'خبرة عملية. تنفيذ يدوم.', servicesText: 'نجمع بين الكوادر والتخطيط والمعدات لتحريك المشاريع الصعبة إلى الأمام.', excavation: 'الحفر والأعمال الترابية', excavationText: 'حفر الصخور الصلبة واللينة والتربة وخطوط الأنابيب والخنادق الكهربائية بدقة.', roads: 'إنشاء الطرق', roadsText: 'طرق معبدة وغير معبدة وفق المواصفات الإقليمية المعتمدة واحتياجات المشروع.', rental: 'تأجير المعدات', rentalText: 'معدات ثقيلة موثوقة مع مشغلين ذوي خبرة وكفاءة عالية.',
    footerText: 'ننفذ مشاريع البنية التحتية المعقدة بإدارة عملية ونزاهة والتزام.', talk: 'تحدث مع فريقنا', findUs: 'موقعنا', contact: 'تواصل', address: 'طريق المطار، أمام مصنع الألبان، بنغازي، ليبيا',
    aboutEyebrow: 'عن الشركة', aboutTitle: 'من نحن', aboutText1: 'شركة بن فضل للمقاولات العامة هي شركة رائدة في الأعمال الترابية والإنشاءات بخبرة تزيد على 30 عاماً في تنفيذ مشاريع البنية التحتية المعقدة في ليبيا.', aboutText2: 'أسلوبنا الإداري الاستباقي ونزاهتنا يقدمان قيمة مستدامة لعملائنا وموردينا وموظفينا.', yearsExperience: 'سنوات الخبرة', skilledOperators: 'مشغلون مهرة', machines: 'معدات ثقيلة', completed: 'مشاريع منجزة', team: 'الفريق الفني', teamText: 'بدعم من السائقين والمشغلين والميكانيكيين وفريق تخطيط متخصص، نحقق الدقة في كل مشروع.', fleet: 'أسطول المعدات', fleetText: 'يشمل أسطولنا حفارات وجرافات وشاحنات قلابات وممهدات ومعدات متخصصة لإنشاء الطرق.',
    contactEyebrow: 'تواصل معنا', contactTitle: 'لنبنِ شيئاً يدوم.', contactText: 'أخبرنا عن مشروعك وسيتواصل معك فريقنا قريباً.', office: 'عنوان المكتب', emailUs: 'راسلنا', callUs: 'اتصل بنا', formTitle: 'اطلب عرض سعر', formText: 'شارك بعض التفاصيل وسنجهز لك الخطوة المناسبة التالية.', success: 'شكراً لك — تم إرسال طلبك. سيتواصل معك فريقنا قريباً.', name: 'الاسم', email: 'البريد الإلكتروني', phone: 'رقم الهاتف', projectType: 'نوع المشروع', projectLocation: 'موقع المشروع', startDate: 'تاريخ البدء المفضل', budget: 'الميزانية التقديرية', subject: 'الموضوع', message: 'أخبرنا عن مشروعك', choose: 'اختر', excavationOption: 'الحفر والأعمال الترابية', roadOption: 'إنشاء الطرق', rentalOption: 'تأجير المعدات', other: 'أخرى', budgetOption1: 'أقل من 50,000 دينار ليبي', budgetOption2: '50,000–150,000 دينار ليبي', budgetOption3: '150,000–500,000 دينار ليبي', budgetOption4: 'أكثر من 500,000 دينار ليبي', send: 'إرسال طلب عرض السعر', privacy: 'بإرسال هذا النموذج، توافق على استخدام بياناتك للرد على استفسارك.',
    whatsapp: 'تواصل عبر واتساب', language: 'English', privacyLink: 'اقرأ سياسة الخصوصية'
  }
};

const LanguageContext = createContext();
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en');
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; localStorage.setItem('language', language); }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage, t: (key) => copy[language][key] }}>{children}</LanguageContext.Provider>;
}
export const useLanguage = () => useContext(LanguageContext);
